# vim: ft=i3
### annoyance specific settings
set $extern "ASUSTek COMPUTER INC PG49WCD R9LMAS003894"
set $extern2 "Dell Inc. DELL P2723DE FLKQ1L3"
# set $main $extern
set $main DP-3

### Output configuration
output $extern mode 5120x1440 position 2560 0
output $extern2 mode 2560x1440 position 0 0

### Window Rules
for_window [title="ContentDialogOverlayWindow"] floating enable

input "1452:613:Apple_Inc._Magic_Trackpad" {
  accel_profile     adaptive
  pointer_accel     0.25
  click_method      clickfinger
  dwt               enabled     # disable while typing
  middle_emulation  enabled
  natural_scroll    enabled
  scroll_method     two_finger
  tap               enabled
  tap_button_map    lrm
}

input "1452:804:Apple_Inc._Magic_Trackpad" {
  accel_profile     adaptive
  pointer_accel     0.25
  click_method      clickfinger
  dwt               enabled     # disable while typing
  middle_emulation  enabled
  natural_scroll    enabled
  scroll_method     two_finger
  tap               enabled
  tap_button_map    lrm
}
