# vim: ft=i3
### bslxkos02 specific settings
set $extern38 "Goldstar Company Ltd 38GN950 008NTLEFY912"
set $extern34 "Dell Inc. DELL U3421WE 6YR9753"
set $extern29 "Lenovo Group Limited L29w-30 UPV08NFA"
set $extern24 "Dell Inc. DELL P2421 7PJG773"
set $port34 DP-1
set $port24 DP-2
set $main $port34

### Output configuration
# output $extern38 mode 3840x1600 position 0 1080
output $extern34 mode 3440x1440 position 0 0
# output $extern29 mode 2560x1080 position 630 0
output $extern24 mode 1920x1200 position 3440 0

for_window [class="Chromium" window_role="pop-up"] floating enable
