### bslxkos03.rsint.net specific settings
# vim: ft=i3
set $intern "Chimei Innolux Corporation 0x1416 0x00000000"
set $extern "ASUSTek COMPUTER INC PG49WCD R9LMAS003894"
set $main eDP-1

### Output configuration
output $intern mode 1920x1080
output $extern mode 5120x1440


bindswitch --reload --locked lid:on output $intern disable
bindswitch --reload --locked lid:off output $intern enable

### Input configuration
input "1160:4122:DELL0A37:00_0488:101A_Touchpad" {
  click_method clickfinger
  dwt enabled               # disable while typing
  # drag enabled
  # drag_lock enabled
  scroll_method two_finger
  tap enabled
  tap_button_map lrm
  natural_scroll enabled
  middle_emulation enabled
}

input "1:1:AT_Translated_Set_2_keyboard" {
  xkb_layout "eu"
  xkb_options "xk5:vim,xk5:fn"
}

for_window [class="Google-chrome" instance="crx_cifhbcnohmdccbgoicgdjpfamggdegmo" window_type="normal"] mark c
for_window [class="Google-chrome" window_role="pop-up"] floating enable
