# vim: ft=i3
### silence specific settings
set $intern "AU Optronics 0x5B2D Unknown"
set $extern "ASUSTek COMPUTER INC PG49WCD R9LMAS003894"
set $main $intern

### Output configuration
output $intern mode 1920x1080
output $extern mode 5120x1440

bindswitch --reload --locked lid:on output $intern disable
bindswitch --reload --locked lid:off output $intern enable

### Input configuration
input "1739:30383:CUST0001:00_06CB:76AF_Touchpad" {
  click_method clickfinger
  dwt enabled               # disable while typing
  # drag enabled
  # drag_lock enabled
  scroll_method two_finger
  tap enabled
  tap_button_map lrm
  natural_scroll enabled
  middle_emulation enabled
}

input "1:1:AT_Translated_Set_2_keyboard" {
  xkb_layout "eu"
  xkb_options "xk5:vim,xk5:fn"
}
