[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"
    # disabled for now, see: https://github.com/twpayne/chezmoi/issues/1614#issuecomment-966524408
    # exact = true
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-completions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-completions.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
{{- $fontDir := ".local/share/fonts" }}
{{- if eq .chezmoi.os "darwin" }}
{{-   $fontDir = "Library/Fonts" }}
{{- end }}
["{{ $fontDir }}/CaskaydiaCoveNerdFontMono-Bold.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/refs/heads/master/patched-fonts/CascadiaCode/CaskaydiaCoveNerdFontMono-Bold.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/CaskaydiaCoveNerdFontMono-BoldItalic.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/refs/heads/master/patched-fonts/CascadiaCode/CaskaydiaCoveNerdFontMono-BoldItalic.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/CaskaydiaCoveNerdFontMono-Italic.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/refs/heads/master/patched-fonts/CascadiaCode/CaskaydiaCoveNerdFontMono-Italic.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/CaskaydiaCoveNerdFontMono-Regular.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/refs/heads/master/patched-fonts/CascadiaCode/CaskaydiaCoveNerdFontMono-Regular.ttf"
    refreshPeriod = "168h"

["{{ $fontDir }}/MesloLGMNerdFontMono-Bold.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/refs/heads/master/patched-fonts/Meslo/M/Bold/MesloLGMNerdFontMono-Bold.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/MesloLGMNerdFontMono-BoldItalic.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/refs/heads/master/patched-fonts/Meslo/M/Bold-Italic/MesloLGMNerdFontMono-BoldItalic.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/MesloLGMNerdFontMono-Italic.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/refs/heads/master/patched-fonts/Meslo/M/Italic/MesloLGMNerdFontMono-Italic.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/MesloLGMNerdFontMono-Regular.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/refs/heads/master/patched-fonts/Meslo/M/Regular/MesloLGMNerdFontMono-Regular.ttf"
    refreshPeriod = "168h"
