position: top
height: 24
start:
- type: workspaces
- type: focused
  icon_size: 16

center:
- type: volume
  sink_slider_orientation: horizontal
  on_click_right: pavucontrol
- type: music

end:
- type: notifications
  on_click_right: swaync-client -C
- type: battery
  show_if: |
    ls /sys/class/power_supply/ | grep --quiet '^BAT'
- type: sys_info
  format:
  - '{cpu_percent}% '
  - '{memory_percent}% '
  interval:
    cpu: 1
  on_click_right: foot -T float btop
- type: tray
- type: clock
  show_week_numbers: true

