general {
    lock_cmd = $HOME/.config/sway/bin/sway_lock lock
    unlock_cmd = $HOME/.config/sway/bin/sway_lock lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = $HOME/.config/sway/bin/sway_lock on
}

# 9 mins: notify warning
listener {
    timeout = 540
    on-timeout = notify-send -r 3 -t 60000  "sleeping soon..."
    on-resume = notify-send -r 3 -t 1000 "welcome back"
}
# 10 mins: Screen Off
listener {
    timeout = 600
    on-timeout = $HOME/.config/sway/bin/sway_lock off
    on-resume = $HOME/.config/sway/bin/sway_lock on
}

# 20 mins: Lock Session
listener {
    timeout = 1200
    on-timeout = loginctl lock-session
}

# # 30 mins: Suspend
# listener {
#     timeout = 1800
#     on-timeout = systemctl suspend
# }
